name: CI

on:
  push:
    branches: [ windows-terminal-ui ]
  pull_request:
    branches: [ windows-terminal-ui ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            set PYTHONPATH=.
            pytest -s -v tests/
          else
            export PYTHONPATH=.
            pytest -s -v tests/
          fi
