name: CI

on:
  push:
    branches: [ windows-terminal-ui ]
  pull_request:
    branches: [ windows-terminal-ui ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint code (flake8)
        run: |
          flake8 .
      - name: Run tests (Linux)
        if: runner.os != 'Windows'
        run: |
          export PYTHONPATH=.
          pytest -s -v tests/
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $env:PYTHONPATH = '.'
          pytest -s -v tests/
      - name: Run tests with coverage (Linux)
        if: runner.os != 'Windows'
        run: |
          export PYTHONPATH=.
          pytest --cov=. --cov-report=xml -s -v tests/
      - name: Run tests with coverage (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $env:PYTHONPATH = '.'
          pytest --cov=. --cov-report=xml -s -v tests/
